### ISSUE TITLE
Enable volume buttons

### ISSUE THREAD

**Issue by opi** [rccavalcanti/pifi-radio#17] opened 2020-10-25 14:10 UTC
(Hi, thanks for this awesome piece of software !)

I wonder how enable the volume buttons ? I guess it is MPD related, maybe something with the mixer configuration, but my knowledge is somehow limited.

thanks

**Comment by rc2dev** [comment] 2020-10-25 16:03
Hi there,

You are correct! That happens because your MPD can't control the volume for some reason. You'll probably have to open `/etc/mpd.conf` and edit the `audio_output` section, specially the mixer related options.

The exact configuration varies according to your system, so I suggest you to look at the MPD documentation [here](https://www.musicpd.org/doc/html/user.html#configuring-audio-outputs) and [here](https://www.musicpd.org/doc/html/plugins.html#output-plugins).

Just to make sure you didn't bump into a bug in PiFi and it's really on the MPD side, can you please do the following?

1. Install mpc with `sudo apt install mpc`
2. Run the following commands and paste the output here:
```
mpc volume
mpc volume 100
mpc volume -10
```

Btw, thanks for the compliment!

**Comment by opi** [comment] 2020-10-25 16:45
I'll look at the MPD documentation about audio output soon. In the meantime, here the output for the `mpc` commands :
```
pi@fipbox:~ $ mpc volume
volume: n/a
pi@fipbox:~ $ 
pi@fipbox:~ $ mpc volume 100
fipreggae-midfi.mp3
[playing] #1/1  48:54/0:00 (0%)
volume: n/a   repeat: off   random: off   single: off   consume: off
pi@fipbox:~ $ 
pi@fipbox:~ $ mpc volume -10
fipreggae-midfi.mp3
[playing] #1/1  48:57/0:00 (0%)
volume: n/a   repeat: off   random: off   single: off   consume: off
```

and my MPD config is simply : 
```
audio_output {
        type            "alsa"
        name            "My ALSA Device"
        device          "hw:0,0"
}
```

I'll try various `mixer_type`, `mixer_device` and `mixer_control` ;

**Comment by rc2dev** [comment] 2020-10-25 16:57
Thanks for pasting the output. This confirms the problem is in the MPD end, probably the configuration.

In case this helps you, I use a USB dongle for audio output, and my config is the following:
```
audio_output {
	type "alsa"
	name "USB audio"
	device "hw:2"
	mixer_type "hardware"
	mixer_device "hw:2"
	mixer_control "Speaker"
}
```

I'm closing the issue as it is not related to PiFi. 

Best regards!

**Closed as completed by rc2dev** 2020-10-25 16:57 UTC

**Comment by crendl** [comment] 2021-03-14 18:46
for what it's worth, after playing around a bit i found the following setting to be working for my setup, which is an old raspberry pi with headphones audio output:

```
audio_output {
        type            "alsa"
        name            "My ALSA Device"
        device          "hw:0"          # optional
        mixer_type      "software"      # optional
        mixer_device    "default"       # optional
        mixer_control   "PCM"           # optional
#       mixer_index     "0"             # optional
}
```
